export const indianStates = [
    { state: "Andhra Pradesh", cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Rajahmundry", "Tirupati", "Anantapur"] },
    { state: "Arunachal Pradesh", cities: ["Itanagar", "Naharlagun", "Pasighat"] },
    { state: "Assam", cities: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon", "Tinsukia"] },
    { state: "Bihar", cities: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia", "Darbhanga", "Arrah"] },
    { state: "Chhattisgarh", cities: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Rajnandgaon", "Jagdalpur"] },
    { state: "Goa", cities: ["Panaji", "Vasco da Gama", "Margao", "Mapusa", "Ponda"] },
    { state: "Gujarat", cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar"] },
    { state: "Haryana", cities: ["Faridabad", "Gurgaon", "Panipat", "Ambala", "Yamunanagar", "Rohtak", "Hisar", "Karnal"] },
    { state: "Himachal Pradesh", cities: ["Shimla", "Dharamshala", "Solan", "Mandi"] },
    { state: "Jharkhand", cities: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar", "Hazaribagh"] },
    { state: "Karnataka", cities: ["Bangalore", "Hubli", "Dharwad", "Mysore", "Gulbarga", "Belgaum", "Mangalore", "Shimoga"] },
    { state: "Kerala", cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Kollam", "Thrissur", "Alappuzha", "Palakkad"] },
    { state: "Madhya Pradesh", cities: ["Indore", "Bhopal", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa"] },
    { state: "Maharashtra", cities: ["Mumbai", "Pune", "Nagpur", "Thane", "Pimpri-Chinchwad", "Nashik", "Kalyan-Dombivli", "Vasai-Virar", "Aurangabad", "Navi Mumbai", "Solapur", "Kolhapur"] },
    { state: "Manipur", cities: ["Imphal"] },
    { state: "Meghalaya", cities: ["Shillong", "Tura"] },
    { state: "Mizoram", cities: ["Aizawl", "Lunglei"] },
    { state: "Nagaland", cities: ["Kohima", "Dimapur"] },
    { state: "Odisha", cities: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri"] },
    { state: "Punjab", cities: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali"] },
    { state: "Rajasthan", cities: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur", "Bhilwara"] },
    { state: "Sikkim", cities: ["Gangtok"] },
    { state: "Tamil Nadu", cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Tiruppur"] },
    { state: "Telangana", cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam"] },
    { state: "Tripura", cities: ["Agartala"] },
    { state: "Uttar Pradesh", cities: ["Lucknow", "Kanpur", "Ghaziabad", "Agra", "Meerut", "Varanasi", "Prayagraj", "Bareilly", "Aligarh", "Noida"] },
    { state: "Uttarakhand", cities: ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur"] },
    { state: "West Bengal", cities: ["Kolkata", "Howrah", "Asansol", "Siliguri", "Durgapur", "Bardhaman", "Malda"] },
    { state: "Andaman and Nicobar Islands", cities: ["Port Blair"] },
    { state: "Chandigarh", cities: ["Chandigarh"] },
    { state: "Dadra and Nagar Haveli and Daman and Diu", cities: ["Daman", "Silvassa"] },
    { state: "Delhi", cities: ["New Delhi", "Delhi", "Dwarka", "Rohini"] },
    { state: "Jammu and Kashmir", cities: ["Srinagar", "Jammu"] },
    { state: "Ladakh", cities: ["Leh", "Kargil"] },
    { state: "Lakshadweep", cities: ["Kavaratti"] },
    { state: "Puducherry", cities: ["Puducherry"] }
];
